Minerva.UI/ViewModels/BuildViewModel.cs
using Minerva.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minerva.UI.ViewModels
{
    public class BuildViewModel
    {
        public string Name { get; set; }

        public List<TestRun> TestRuns { get; set; }

        public string GetLabelsAsArray()
        {
            var runLabels = TestRuns.Select(r => r.RunAt.ToString()).ToArray();
            var stringArray = string.Join(",", runLabels);
            return stringArray;
        }

        public string GetPassesAsArray()
        {
            var passes = TestRuns.Select(r => r.Passes).ToArray();
            var stringArray = string.Join(",", passes);
            return stringArray;
        }

        public string GetFailsAsArray()
        {
            var fails = TestRuns.Select(r => r.Fails).ToArray();
            var stringArray = string.Join(",", fails);
            return stringArray;
        }

        public string GetSkipsAsArray()
        {
            var skips = TestRuns.Select(r => r.Skips).ToArray();
            var stringArray = string.Join(",", skips);
            return stringArray;
        }
    }

}

Minerva.UI/ViewModels/Builds.cs
using Minerva.UI.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minerva.UI.ViewModels
{
    public enum Builds
    {
        [StringValue("DefCore-2015.05")]
        DefCore052015,
        [StringValue("DefCore-2015.07")]
        DefCore072015,
        [StringValue("DefCore-2016.next")]
        DefCore2016Next

    }

}

Minerva.UI/ViewModels/BuildsViewModel.cs
using Minerva.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Minerva.UI.ViewModels
{
    public class BuildsViewModel
    {
        public string BuildName { get; set; }

        public TestRun LastTestRun { get; set; }

        public List<Dictionary<string, string>> GetChartData()
        {
            var passDict = new Dictionary<string, string>
            {
                ["value"] = LastTestRun.Passes.ToString(),
                ["color"] = "green"
            };

            var failDict = new Dictionary<string, string>
            {
                ["value"] = LastTestRun.Fails.ToString(),
                ["color"] = "red"
            };

            var skipsDict = new Dictionary<string, string>
            {
                ["value"] = LastTestRun.Skips.ToString(),
                ["color"] = "yellow"
            };

            var chartData = new List<Dictionary<string, string>>
            {
                passDict, failDict, skipsDict
            };

            return chartData;
        }
    }

}

Minerva.UI/Controllers/BuildsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Minerva.UI.Services;
using Minerva.UI.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Minerva.UI.Controllers
{
    public class BuildsController : Controller
    {
        private readonly IMetricsService _metricsService;

        public BuildsController(IMetricsService metricsService)
        {
            _metricsService = metricsService;
        }

        public async Task<IActionResult> Index()
        {
            string[] builds = { "DefCore-2016.01-All", "Tempest-All-Tests" };

            var model = new List<BuildsViewModel>();
            foreach (var build in builds)
            {
                var testRuns = await _metricsService.GetRunsByBuildNameAsync(build);
                var lastRun = testRuns.OrderByDescending(r => r.RunAt).FirstOrDefault();
                var buildVM = new BuildsViewModel
                {
                    BuildName = build,
                    LastTestRun = lastRun
                };
                model.Add(buildVM);
            }

            return View(model);
        }

        public async Task<IActionResult> Details(string name)
        {
            var runs = await _metricsService.GetRunsByBuildNameAsync(name);
            var model = new BuildViewModel
            {
                Name = name,
                TestRuns = runs.OrderByDescending(r => r.RunAt).ToList()
            };
            return View(model);
        }

    }
}

Minerva.UI/Controllers/TestRunsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Minerva.UI.Services;
using Minerva.UI.ViewModels;
using Minerva.UI.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Minerva.UI.Controllers
{
    public class TestRunsController : Controller
    {
        private readonly IMetricsService _metricsService;

        public TestRunsController(IMetricsService metricsService)
        {
            _metricsService = metricsService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _metricsService.GetTestRunsAsync();
            return View(model.OrderByDescending(r => r.RunAt).ToList());

        }

        public async Task<IActionResult> Details(string id)
        {
            var model = await _metricsService.GetTestResultsByRunId(id);
            return View(model);
        }

    }
}

Minerva.UI/Views/Builds/Details.cshtml
@using Minerva.UI.ViewModels
@model BuildViewModel

<h2>Test Runs for @Model.Name</h2>

<script src="~/lib/chart.js/dist/Chart.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

<div id="summary" data-labels="@Model.GetLabelsAsArray()" data-passes="@Model.GetPassesAsArray()" data-fails="@Model.GetFailsAsArray()" data-skips="@Model.GetSkipsAsArray()">

</div>

<canvas id="results-line" height="300" width="800"></canvas>
<script type="text/javascript">
    $(document).ready(function () {

        var data = {
            labels: '@Model.GetLabelsAsArray()'.split(","),
            datasets: [
                {
                    label: "Passes",
                    fill: false,
                    tension: 0.07,
                    backgroundColor: "rgba(6,252,30,0.4)",
                    borderColor: "rgba(6,252,30,0.4)",
                    borderCapStyle: 'butt',
                    borderDash: [],
                    borderDashOffset: 0.0,
                    borderJoinStyle: 'miter',
                    pointBorderColor: "rgba(6,252,30,0.4)",
                    pointBackgroundColor: "#fff",
                    pointBorderWidth: 1,
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: "rgba(6,252,30,0.4)",
                    pointHoverBorderColor: "rgba(6,252,30,0.4)",
                    pointHoverBorderWidth: 2,
                    pointRadius: 1,
                    pointHitRadius: 10,

                    data: [ @Model.GetPassesAsArray() ]
                },
                {
                    label: "Fails",
                    fill: false,
                    tension: 0.07,
                    backgroundColor: "rgba(255,0,60,0.4)",
                    borderColor: "rgba(255,0,60,0.4)",
                    borderCapStyle: 'butt',
                    borderDash: [],
                    borderDashOffset: 0.0,
                    borderJoinStyle: 'miter',
                    pointBorderColor: "rgba(255,0,60,0.4)",
                    pointBackgroundColor: "#fff",
                    pointBorderWidth: 1,
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: "rgba(255,0,60,0.4)",
                    pointHoverBorderColor: "rgba(255,0,60,0.4)",
                    pointHoverBorderWidth: 2,
                    pointRadius: 1,
                    pointHitRadius: 10,

                    data: [ @Model.GetFailsAsArray() ]
                },
                {
                    label: "Skips",
                    fill: false,
                    tension: 0.07,
                    backgroundColor: "rgba(239,247,0,0.4)",
                    borderColor: "rgba(239,247,0,0.4)",
                    borderCapStyle: 'butt',
                    borderDash: [],
                    borderDashOffset: 0.0,
                    borderJoinStyle: 'miter',
                    pointBorderColor: "rgba(239,247,0,0.4)",
                    pointBackgroundColor: "#fff",
                    pointBorderWidth: 1,
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: "rgba(239,247,0,0.4)",
                    pointHoverBorderColor: "rgba(239,247,0,0.4)",
                    pointHoverBorderWidth: 2,
                    pointRadius: 1,
                    pointHitRadius: 10,

                    data: [ @Model.GetSkipsAsArray() ]
                }
            ]
        };
        var ctx = $("#results-line").get(0).getContext("2d");
        var myDoughnut = Chart.Line(ctx, { data: data });
    });

</script>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Test Run ID</th>
            <th>Date Executed</th>
            <th>Passes</th>
            <th>Fails</th>
            <th>Skips</th>
            <th>Total Execution Time</th>
        </tr>
    </thead>
    @foreach (var test in Model.TestRuns)
    {
        <tr>
            <td><a asp-controller="TestRuns" asp-action="Details" asp-route-id="@test.Id">@test.Id</a></td>
            <td>@test.RunAt</td>
            <td>@test.Passes</td>
            <td>@test.Fails</td>
            <td>@test.Skips</td>
            <td>@test.GetHumanRunTime()</td>
        </tr>
    }

</table>

Minerva.UI/Views/Builds/Index.cshtml
@using Minerva.UI.ViewModels

@model List<BuildsViewModel>

<h2>Builds</h2>

<script src="~/lib/chart.js/dist/Chart.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

<div class="container">
    <div class="row">
        @foreach (var build in Model)
        {
            <div class="col-md-6" id="build-@build.LastTestRun.Id" data-passes="@build.LastTestRun.Passes" data-skips="@build.LastTestRun.Skips" data-failures="@build.LastTestRun.Fails">
                <div class="panel panel-default">
                    <div class="panel-heading panel-success">
                        <a asp-controller="Builds" asp-action="Details" asp-route-name="@build.BuildName">@build.BuildName</a>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8">
                                <table class="table table-bordered table-condensed pull-left">
                                    <tr>
                                        <td>Last Executed</td>
                                        <td>@build.LastTestRun.GetHumanRunAt()</td>
                                    </tr>
                                    <tr>
                                        <td>Tests Passed</td>
                                        <td>@build.LastTestRun.Passes</td>
                                    </tr>
                                    <tr>
                                        <td>Tests Failed</td>
                                        <td>@build.LastTestRun.Fails</td>
                                    </tr>
                                    <tr>
                                        <td>Tests Skipped</td>
                                        <td>@build.LastTestRun.Skips</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-md-4">
                                <canvas id="doughnut-@build.BuildName" height="100" width="100"></canvas>
                            </div>
                        </div>

                        <script type="text/javascript">
                            $(document).ready(function () {

                                var test_run = document.getElementById('build-@build.LastTestRun.Id');


                                var data = {
                                    labels: [
                                        "passed",
                                        "failed",
                                        "skipped"
                                    ],
                                    datasets: [
                                        {
                                            data: [
                                                parseInt(test_run.getAttribute('data-passes')),
                                                parseInt(test_run.getAttribute('data-failures')),
                                                parseInt(test_run.getAttribute('data-skips'))
                                            ],
                                            backgroundColor: [
                                                "green",
                                                "red",
                                                "yellow"
                                            ]

                                        }
                                    ]
                                };

                                var myDoughnut = new Chart(document.getElementById("doughnut-@build.BuildName"), { type: 'doughnut', data: data, options: { legend: {display: false}} });
                            });

                        </script>
                    </div>
                </div>
            </div>
        }
    </div>
</div>